font_family      JetBrainsMono Nerd Font Mono
font_size        11.0
disable_ligatures always
cursor_shape     beam
window_padding_width 8
confirm_os_window_close 0

# gruvbox dark hard
background  #1d2021
foreground  #ebdbb2

color0  #282828
color1  #cc241d
color2  #98971a
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #a89984

color8  #928374
color9  #fb4934
color10 #b8bb26
color11 #fabd2f
color12 #83a598
color13 #d3869b
color14 #8ec07c
color15 #ebdbb2

# cursor
cursor            #d79921
cursor_text_color #1d2021

# selection
selection_background #d79921
selection_foreground #1d2021

# disable splits — tmux handles everything
map ctrl+shift+enter no_op
map ctrl+shift+t      no_op
